# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4be684f71956d6c82959bb8f3eddd7072342d252f3e74933e55d2d38af583ece302d2cc329b14f14cd079d308e2276154fadc366942fa4380e182fc13f52ce65

test:
  secret_key_base: 990e641311dc29eb1d5d2eb34e732f3aada9c666c15200cd14746dff89fb9d49aef4a56c37c2d7206c40281d8d5cd8e534773c431cbcfe16958a338370f7bca0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
